# Generated by Django 4.2.7 on 2023-11-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Interior', 'Interior'), ('Direccion', 'Direccion'), ('Embrague', 'Embrague'), ('Motor', 'Motor'), ('Freno', 'Freno'), ('Alumbrado', 'Alumbrado'), ('Carroceria', 'Carroceria')], default='Interior', max_length=15)),
                ('marca', models.CharField(choices=[('Seat', 'Seat'), ('Audi', 'Audi'), ('Toyota', 'Toyota'), ('Mini', 'Mini'), ('Honda', 'Honda'), ('Fiat', 'Fiat')], default='Seat', max_length=10)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('imagen', models.URLField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
