# Generated by Django 4.2.5 on 2023-12-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamaciones', '0002_reclamacion_descripcion_alter_reclamacion_motivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamacion',
            name='usuario',
        ),
    ]
