# Generated by Django 4.2.7 on 2023-11-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piezasRevive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='forma_entrega',
            field=models.CharField(choices=[('express', 'express'), ('normal', 'normal')], default='normal', max_length=15),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='forma_pago',
            field=models.CharField(choices=[('contrareembolso', 'contrareembolso'), ('tarjeta', 'tarjeta')], default='contrareembolso', max_length=15),
        ),
    ]
