# Generated by Django 4.2.7 on 2023-11-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piezasRevive', '0002_perfilusuario_forma_entrega_perfilusuario_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='domicilio',
            field=models.CharField(default='Avenida Reina Mercedes S/N ETSII', max_length=150),
        ),
    ]
