# Generated by Django 4.2.7 on 2023-11-24 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=100)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('estado_pedido', models.CharField(choices=[('en_espera', 'en_espera'), ('enviado', 'enviado'), ('entregado', 'entregado')], default='en_espera', max_length=10)),
                ('forma_pago', models.CharField(choices=[('contrareembolso', 'contrareembolso'), ('tarjeta', 'tarjeta')], default='contrareembolso', max_length=15)),
                ('forma_entrega', models.CharField(choices=[('express', 'express'), ('normal', 'normal')], default='normal', max_length=15)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'pedidos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
            options={
                'verbose_name': 'Item Pedido',
                'verbose_name_plural': 'Items Pedidos',
                'db_table': 'itemspedido',
                'ordering': ['id'],
            },
        ),
    ]
