# Generated by Django 4.2.7 on 2023-11-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='gastos_envio',
            field=models.IntegerField(default=0),
        ),
    ]
