# Generated by Django 4.2.7 on 2023-12-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_pedido_precio_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega_estimada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
